COLOR_OK     = "green"
COLOR_ERROR  = "red"
COLOR_WARN   = "yellow"
COLOR_NORMAL = "white"
COLOR_NONE   = "black"

COLOR_OK_BACK     = f"on_{COLOR_OK}"
COLOR_ERROR_BACK  = f"on_{COLOR_ERROR}"
COLOR_WARN_BACK   = f"on_{COLOR_WARN}"
COLOR_NORMAL_BACK = f"on_{COLOR_NORMAL}"
COLOR_NONE_BACK   = f"on_{COLOR_NONE}"

VISITED_ATTR = "visited"
